# Generated by Django 5.0.9 on 2025-03-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
        ('managerdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.AlterField(
            model_name='form',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerdashboard.manager'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_data',
            field=models.JSONField(default=list),
        ),
    ]
