# Generated by Django 5.0.9 on 2025-04-02 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_rename_creator_form_created_by_form_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsubmission',
            options={},
        ),
        migrations.RenameField(
            model_name='formsubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='form',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='form',
            name='responses_count',
        ),
        migrations.RemoveField(
            model_name='form',
            name='status',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='submitted_data',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='form',
            name='fields',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='form',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='responses',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
